name: error-collector

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: app/error-collector/.build
          key: swift-${{ runner.os }}-build
      - name: Build
        run: cd app/error-collector && swift build
